### ISSUE TITLE
NuGet Package Doesn't Work Right

### ISSUE THREAD

**Issue by adamcaudill** [adamcaudill/Base58Check#2]
The package isn't setup right - try again.

**Comment by bitbeans** [comment]
It seems there is a problem with the .NET version of the package? I also have problems to install it.

**Comment by bitbeans** [comment]
I think you just need to add a **lib/net** folder and put the Base58Check.dll inside.

I use this dll in some projects, but i still can not use the nuget package. :)

**Comment by adamcaudill** [comment]
For some reason I thought I had already fixed this. 

Should be a simple fix, I'll get it done soon.

**Comment by richardschneider** [comment]
pls fix, I would like to use as NuGet instead of copy and paste.

**Comment by adamcaudill** [comment]
I think this is fixed now.

https://www.nuget.org/packages/Base58Check/0.2.0

**Comment by bitbeans** [comment]
:+1: works! thank you very much!

**Comment by richardschneider** [comment]
thanks
